package cal.cxf.konghao.org;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import org.konghao.ws.User;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2012-07-12T15:19:21.468+08:00
 * Generated source version: 2.6.1
 * 
 */
@WebService(targetNamespace = "http://org.konghao.cxf.cal/", name = "ICalWsService")
public interface ICalWsService {

    @WebResult(name = "rel", targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://org.konghao.cxf.cal/")
    @WebMethod
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://org.konghao.cxf.cal/")
    public int add(
        @WebParam(name = "num1", targetNamespace = "")
        int num1,
        @WebParam(name = "num2", targetNamespace = "")
        int num2,
        @WebParam(name="licenseUser",header=true)
        User licenseUser
    );
}
