package cal.cxf.konghao.org;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

import org.apache.cxf.interceptor.OutInterceptors;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2012-07-12T15:51:35.796+08:00
 * Generated source version: 2.6.1
 * 
 */
@WebServiceClient(name = "CalWsService", 
                  wsdlLocation = "http://localhost:8889/ms?wsdl",
                  targetNamespace = "http://org.konghao.cxf.cal/")
@OutInterceptors(interceptors={"org.konghao.ws.interceptor.LicenseUserOutInter"})
public class CalWsService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://org.konghao.cxf.cal/", "CalWsService");
    public final static QName CalWsPort = new QName("http://org.konghao.cxf.cal/", "calWsPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8889/ms?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CalWsService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8889/ms?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CalWsService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CalWsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CalWsService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CalWsService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CalWsService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CalWsService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ICalWsService
     */
    @WebEndpoint(name = "calWsPort")
    public ICalWsService getCalWsPort() {
        return super.getPort(CalWsPort, ICalWsService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ICalWsService
     */
    @WebEndpoint(name = "calWsPort")
    public ICalWsService getCalWsPort(WebServiceFeature... features) {
        return super.getPort(CalWsPort, ICalWsService.class, features);
    }

}
