package cal.cxf.konghao.org;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import org.apache.cxf.interceptor.OutInterceptors;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2012-07-12T15:51:35.796+08:00
 * Generated source version: 2.6.1
 * 
 */
@WebService(targetNamespace = "http://org.konghao.cxf.cal/", name = "ICalWsService")
@XmlSeeAlso({ObjectFactory.class})
@OutInterceptors(interceptors={"org.konghao.ws.interceptor.LicenseUserOutInter"})
public interface ICalWsService {

    @WebResult(name = "rel", targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://org.konghao.cxf.cal/", className = "cal.cxf.konghao.org.Add")
    @WebMethod
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://org.konghao.cxf.cal/", className = "cal.cxf.konghao.org.AddResponse")
    public int add(
        @WebParam(name = "num1", targetNamespace = "")
        int num1,
        @WebParam(name = "num2", targetNamespace = "")
        int num2
    );
}
