
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package cal.cxf.konghao.org;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2012-07-12T15:51:35.734+08:00
 * Generated source version: 2.6.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "CalWsService",
                      portName = "calWsPort",
                      targetNamespace = "http://org.konghao.cxf.cal/",
                      wsdlLocation = "http://localhost:8889/ms?wsdl",
                      endpointInterface = "cal.cxf.konghao.org.ICalWsService")
                      
public class ICalWsServiceImpl implements ICalWsService {

    private static final Logger LOG = Logger.getLogger(ICalWsServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see cal.cxf.konghao.org.ICalWsService#add(int  num1 ,)int  num2 )*
     */
    public int add(int num1,int num2) { 
        LOG.info("Executing operation add");
        System.out.println(num1);
        System.out.println(num2);
        try {
            int _return = 0;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
