
package org.konghao.student.ws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "StudentWsException", targetNamespace = "http://ws.student.konghao.org")
public class StudentWsException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private StudentWsException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public StudentWsException_Exception(String message, StudentWsException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public StudentWsException_Exception(String message, StudentWsException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.konghao.student.ws.StudentWsException
     */
    public StudentWsException getFaultInfo() {
        return faultInfo;
    }

}
