package org.konghao.student.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by Apache CXF 2.6.1
 * 2012-07-12T16:22:28.078+08:00
 * Generated source version: 2.6.1
 * 
 */
@WebService(targetNamespace = "http://ws.student.konghao.org", name = "IStudentWsService")
@XmlSeeAlso({ObjectFactory.class})
//@OutInterceptors(interceptors={"org.konghao.student.ws.interceptor.LicenseInfoOutHandler"})
public interface IStudentWsService {

    @WebResult(name = "stus", targetNamespace = "")
    @RequestWrapper(localName = "listPunishStu", targetNamespace = "http://ws.student.konghao.org", className = "org.konghao.student.ws.ListPunishStu")
    @WebMethod
    @ResponseWrapper(localName = "listPunishStuResponse", targetNamespace = "http://ws.student.konghao.org", className = "org.konghao.student.ws.ListPunishStuResponse")
    public java.util.List<org.konghao.student.ws.Student> listPunishStu(
        @WebParam(name = "year", targetNamespace = "")
        int year,
        @WebParam(name = "semester", targetNamespace = "")
        java.lang.String semester
    );

    @WebResult(name = "stus", targetNamespace = "")
    @RequestWrapper(localName = "listRewardStu", targetNamespace = "http://ws.student.konghao.org", className = "org.konghao.student.ws.ListRewardStu")
    @WebMethod
    @ResponseWrapper(localName = "listRewardStuResponse", targetNamespace = "http://ws.student.konghao.org", className = "org.konghao.student.ws.ListRewardStuResponse")
    public java.util.List<org.konghao.student.ws.Student> listRewardStu(
        @WebParam(name = "year", targetNamespace = "")
        int year,
        @WebParam(name = "semester", targetNamespace = "")
        java.lang.String semester
    );

    @WebResult(name = "student", targetNamespace = "")
    @RequestWrapper(localName = "getStudent", targetNamespace = "http://ws.student.konghao.org", className = "org.konghao.student.ws.GetStudent")
    @WebMethod
    @ResponseWrapper(localName = "getStudentResponse", targetNamespace = "http://ws.student.konghao.org", className = "org.konghao.student.ws.GetStudentResponse")
    public org.konghao.student.ws.Student getStudent(
        @WebParam(name = "xh", targetNamespace = "")
        java.lang.String xh
    ) throws StudentWsException_Exception;

    @WebResult(name = "rp", targetNamespace = "")
    @RequestWrapper(localName = "listRpByStu", targetNamespace = "http://ws.student.konghao.org", className = "org.konghao.student.ws.ListRpByStu")
    @WebMethod
    @ResponseWrapper(localName = "listRpByStuResponse", targetNamespace = "http://ws.student.konghao.org", className = "org.konghao.student.ws.ListRpByStuResponse")
    public java.util.List<org.konghao.student.ws.RewardPunish> listRpByStu(
        @WebParam(name = "xh", targetNamespace = "")
        java.lang.String xh
    );
}
