package org.konghao.student.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2012-07-12T16:22:28.093+08:00
 * Generated source version: 2.6.1
 * 
 */
@WebServiceClient(name = "StudentWsService", 
                  wsdlLocation = "http://localhost:8787/stu/services/ss?wsdl",
                  targetNamespace = "http://ws.student.konghao.org") 
public class StudentWsService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.student.konghao.org", "StudentWsService");
    public final static QName StudentWsServicePort = new QName("http://ws.student.konghao.org", "StudentWsServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8787/stu/services/ss?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(StudentWsService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8787/stu/services/ss?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public StudentWsService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public StudentWsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StudentWsService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public StudentWsService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public StudentWsService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public StudentWsService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns IStudentWsService
     */
    @WebEndpoint(name = "StudentWsServicePort")
    public IStudentWsService getStudentWsServicePort() {
        return super.getPort(StudentWsServicePort, IStudentWsService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IStudentWsService
     */
    @WebEndpoint(name = "StudentWsServicePort")
    public IStudentWsService getStudentWsServicePort(WebServiceFeature... features) {
        return super.getPort(StudentWsServicePort, IStudentWsService.class, features);
    }

}
