
package org.konghao.student.ws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.6.1
 * 2012-07-12T16:22:28.031+08:00
 * Generated source version: 2.6.1
 */

@WebFault(name = "StudentWsException", targetNamespace = "http://ws.student.konghao.org")
public class StudentWsException_Exception extends Exception {
    
    private org.konghao.student.ws.StudentWsException studentWsException;

    public StudentWsException_Exception() {
        super();
    }
    
    public StudentWsException_Exception(String message) {
        super(message);
    }
    
    public StudentWsException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public StudentWsException_Exception(String message, org.konghao.student.ws.StudentWsException studentWsException) {
        super(message);
        this.studentWsException = studentWsException;
    }

    public StudentWsException_Exception(String message, org.konghao.student.ws.StudentWsException studentWsException, Throwable cause) {
        super(message, cause);
        this.studentWsException = studentWsException;
    }

    public org.konghao.student.ws.StudentWsException getFaultInfo() {
        return this.studentWsException;
    }
}
