
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package org.konghao.ws;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2012-07-11T17:20:40.250+08:00
 * Generated source version: 2.6.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "IMyServiceService",
                      portName = "IMyServicePort",
                      targetNamespace = "http://ws.konghao.org/",
                      wsdlLocation = "http://localhost:8878/ms?wsdl",
                      endpointInterface = "org.konghao.ws.IMyService")
                      
public class IMyServiceImpl implements IMyService {

    private static final Logger LOG = Logger.getLogger(IMyServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see org.konghao.ws.IMyService#sayHello(java.lang.String  name )*
     */
    public java.lang.String sayHello(java.lang.String name) { 
        LOG.info("Executing operation sayHello");
        System.out.println(name);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
