package org.konghao.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2012-07-11T17:20:40.312+08:00
 * Generated source version: 2.6.1
 * 
 */
@WebService(targetNamespace = "http://ws.konghao.org/", name = "IMyService")
@XmlSeeAlso({ObjectFactory.class})
public interface IMyService {

    @WebResult(name = "hello", targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://ws.konghao.org/", className = "org.konghao.ws.SayHello")
    @WebMethod
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://ws.konghao.org/", className = "org.konghao.ws.SayHelloResponse")
    public java.lang.String sayHello(
        @WebParam(name = "name", targetNamespace = "")
        java.lang.String name
    );
}
